// Barrel file for container components, which will be used to compose our App component, which will be the root component we will pass to the ReactDOM render call;
export { default as AllCampusesContainer } from './campus/AllCampusesContainer';
export { default as CampusContainer } from './campus/CampusContainer';
export { default as AddCampusFormContainer } from './campus/AddCampusFormContainer';
export { default as EditCampusFormContainer } from './campus/EditCampusFormContainer';
export { default as AllStudentsContainer } from './student/AllStudentsContainer';
export { default as StudentContainer } from './student/StudentContainer';
export { default as AddStudentFormContainer } from './student/AddStudentFormContainer';
export { default as EditStudentFormContainer } from './student/EditStudentFormContainer';
export { default as NavBarContainer } from './NavBarContainer';
